version: "3.9"

services:
  attack:
    build: .
    volumes:
      - ./data:/app/data
    networks:
      - attack_network

networks:
  attack_network:
    name: attack_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-attack
